domain: homeassistant
service: reload_config_entry
name: Reload config entry
description: Reloads the specified config entry.
fields:
  entry_id:
    required: false
    name: Config entry ID
    description: The configuration entry ID of the entry to be reloaded.
    selector:
      config_entry: {}
target:
  entity:
  - {}
  device:
  - {}
handler: builtin:service.not_implemented
supports_response: false
